version: '3.9'
services:
  db:
    image: postgres:10.4
    ports:
      - 8001:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  tichu-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 8000:${HTTP_PORT}
    depends_on:
      - db
    entrypoint:
      - /home/node/app/entrypoint.sh

networks:
  tichu-network:

volumes:
  tichu-volume:
